version: 0.2

env: 
  variables:
    AMZLINUX_CONTAINER_REVISION: "0b9e43b"
    IMAGE_TAG: "latest"
   

phases:
  pre_build:
    commands:
      - uname -a
      - cat /etc/lsb-release
      - env
      - bash -x ./setup.sh
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd amazon-linux-docker-images && docker build -t ${IMAGE_REPO_NAME} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
