version: 0.2

env: 
  variables:
    AMZLINUX_CONTAINER_REVISION: "0b9e43b"
    IMAGE_TAG: "latest"
   

phases:
  pre_build:
    commands:
      - uname -a
      - cat /etc/lsb-release
      - env
      - bash -x ./setup.sh
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls -la /bin/sh
      #- bash -c 'echo ${ECR_REPO_URL}:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}'
      - cd amazon-linux-docker-images && docker build -t ${ECR_REPO_URL}:${IMAGE_TAG} -t ${ECR_REPO_URL}:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | awk '{string=substr($0, 1, 7); print string;}') .
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECR_REPO_URL}:${IMAGE_TAG}
      - docker push ${ECR_REPO_URL}:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | awk '{string=substr($0, 1, 7); print string;}')
      - echo finished

